# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:
    from . import blimsphere_pb2 as blimsphere__pb2
except ImportError:
    import blimsphere_pb2 as blimsphere__pb2


class AuthenticationServiceStub(object):
    """Authentication Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/blimsphere.AuthenticationService/Enroll',
                request_serializer=blimsphere__pb2.EnrollRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.EnrollResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/blimsphere.AuthenticationService/Login',
                request_serializer=blimsphere__pb2.LoginRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.LoginResponse.FromString,
                )
        self.RequestOTP = channel.unary_unary(
                '/blimsphere.AuthenticationService/RequestOTP',
                request_serializer=blimsphere__pb2.OTPRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.OTPResponse.FromString,
                )
        self.VerifyOTP = channel.unary_unary(
                '/blimsphere.AuthenticationService/VerifyOTP',
                request_serializer=blimsphere__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.VerifyOTPResponse.FromString,
                )


class AuthenticationServiceServicer(object):
    """Authentication Service
    """

    def Enroll(self, request, context):
        """User enrollment/registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Login with username and password
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOTP(self, request, context):
        """Request OTP for login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Verify OTP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=blimsphere__pb2.EnrollRequest.FromString,
                    response_serializer=blimsphere__pb2.EnrollResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=blimsphere__pb2.LoginRequest.FromString,
                    response_serializer=blimsphere__pb2.LoginResponse.SerializeToString,
            ),
            'RequestOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOTP,
                    request_deserializer=blimsphere__pb2.OTPRequest.FromString,
                    response_serializer=blimsphere__pb2.OTPResponse.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=blimsphere__pb2.VerifyOTPRequest.FromString,
                    response_serializer=blimsphere__pb2.VerifyOTPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blimsphere.AuthenticationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthenticationService(object):
    """Authentication Service
    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.AuthenticationService/Enroll',
            blimsphere__pb2.EnrollRequest.SerializeToString,
            blimsphere__pb2.EnrollResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.AuthenticationService/Login',
            blimsphere__pb2.LoginRequest.SerializeToString,
            blimsphere__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.AuthenticationService/RequestOTP',
            blimsphere__pb2.OTPRequest.SerializeToString,
            blimsphere__pb2.OTPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.AuthenticationService/VerifyOTP',
            blimsphere__pb2.VerifyOTPRequest.SerializeToString,
            blimsphere__pb2.VerifyOTPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileServiceStub(object):
    """File Operations Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/blimsphere.FileService/UploadFile',
                request_serializer=blimsphere__pb2.FileChunk.SerializeToString,
                response_deserializer=blimsphere__pb2.UploadResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/blimsphere.FileService/DownloadFile',
                request_serializer=blimsphere__pb2.DownloadRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.FileChunk.FromString,
                )
        self.ListFiles = channel.unary_unary(
                '/blimsphere.FileService/ListFiles',
                request_serializer=blimsphere__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.ListFilesResponse.FromString,
                )
        self.GetStorageInfo = channel.unary_unary(
                '/blimsphere.FileService/GetStorageInfo',
                request_serializer=blimsphere__pb2.StorageInfoRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.StorageInfoResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/blimsphere.FileService/DeleteFile',
                request_serializer=blimsphere__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=blimsphere__pb2.DeleteFileResponse.FromString,
                )


class FileServiceServicer(object):
    """File Operations Service
    """

    def UploadFile(self, request_iterator, context):
        """Upload file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Download file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """List user files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageInfo(self, request, context):
        """Get storage information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=blimsphere__pb2.FileChunk.FromString,
                    response_serializer=blimsphere__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=blimsphere__pb2.DownloadRequest.FromString,
                    response_serializer=blimsphere__pb2.FileChunk.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=blimsphere__pb2.ListFilesRequest.FromString,
                    response_serializer=blimsphere__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetStorageInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageInfo,
                    request_deserializer=blimsphere__pb2.StorageInfoRequest.FromString,
                    response_serializer=blimsphere__pb2.StorageInfoResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=blimsphere__pb2.DeleteFileRequest.FromString,
                    response_serializer=blimsphere__pb2.DeleteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blimsphere.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """File Operations Service
    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/blimsphere.FileService/UploadFile',
            blimsphere__pb2.FileChunk.SerializeToString,
            blimsphere__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/blimsphere.FileService/DownloadFile',
            blimsphere__pb2.DownloadRequest.SerializeToString,
            blimsphere__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.FileService/ListFiles',
            blimsphere__pb2.ListFilesRequest.SerializeToString,
            blimsphere__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStorageInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.FileService/GetStorageInfo',
            blimsphere__pb2.StorageInfoRequest.SerializeToString,
            blimsphere__pb2.StorageInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blimsphere.FileService/DeleteFile',
            blimsphere__pb2.DeleteFileRequest.SerializeToString,
            blimsphere__pb2.DeleteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
